apiVersion: v1
kind: Config
clusters:
- cluster:
  name: localmachine_cluster
    server: https://192.168.99.100:8443
    certificate-authority: /path/to/ca.crt 

- cluster:
  name: aws_cluster
    server: https://aws.com
    certificate-authority: /path/to/ca.crt 

contexts:
- context:
    cluster: localmachine_cluster
    users: ay

- context:
    cluster: aws_cluster
    users: other_user

- name: ay 
  user:
    clicent-key: /path/to/client.key
    client-certificate: /path/to/client.crt

- name: other_user 
  user:
    clicent-key: /different/path/to/client.key
    client-certificate: /different/path/to/client.crt
