apiVersion: v1
kind: Pod       #Type of Resource.. Name starts with Capital
metadata:
  name: myweb-pod3
  labels:
    env: testing
    region: IN    

spec:           #Specification of the Pod Can contain multiple container or single container pod
  containers:
  - name: myweb-con
    image: httpd
