apiVersion: v1
kind: Pod       #Type of Resource.. Name starts with Capital
metadata:
  name: myweb-pod
  labels:
    country: IN
    name: myweb
    dc: '2'    

spec:           #Specification of the Pod Can contain multiple container or single container pod
  containers:
  - name: myweb-con
    image: httpd
    volumeMounts:
      - name: web-vol1
        mountPath: /var/www/html

  volumes:
  - name: web-vol1
    persistentVolumeClaim:
      claimName: web-pvc1