apiVersion: v1
kind:  ReplicationController
metadata:
  name:  myweb-rc

spec:
  replicas:  3
  selector:
    env: production
  template:
    metadata:
      name: myweb-pod
      labels:
        env: production
    spec:           #Specification of the Pod Can contain multiple container or single container pod
      containers:
        - name: myweb-con
          image: httpd
